Setup
skbkontur/form-engine pull request #1
Opened 2021-04-07 11:40 UTC by RomanKhasanov

2021-04-07 12:09 UTC, fakefeik requested changes

2021-04-07 12:09 UTC, fakefeik commented on appveyor.yml
> +  NODEJS_VERSION: 12
убрать может?

2021-04-07 12:09 UTC, fakefeik commented on package.json
> +    "@babel/generator": "^7.12.17",
тут какой-то мусор в зависимостях кажется

2021-04-07 12:09 UTC, fakefeik commented on package.json
> +    "jest-teamcity-reporter": "^0.9.0",
зачем teamcity reporter?

2021-04-08 06:27 UTC, RomanKhasanov commented on package.json
> +    "@babel/generator": "^7.12.17",
он используется

2021-04-08 06:34 UTC, RomanKhasanov commented on appveyor.yml
> +  NODEJS_VERSION: 12
попробовал, там что-то с npm не то, пока оставил 12

2021-04-08 06:35 UTC, RomanKhasanov commented on package.json
> +    "jest-teamcity-reporter": "^0.9.0",
удалил

2021-04-08 06:51 UTC, fakefeik commented on package.json
> +    "@babel/generator": "^7.12.17",
в тестах же только? предлагаю унести в devDependencies

2021-04-08 06:59 UTC, RomanKhasanov commented on package.json
> +    "@babel/generator": "^7.12.17",
готово

2021-04-08 07:18 UTC, fakefeik approved these changes

2021-04-08 08:09 UTC, merged